# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
   config,
   lib,
   pkgs,
   modulesPath,
   ...
}:

{
   imports = [
      (modulesPath + "/installer/scan/not-detected.nix")
      ./boot.nix
   ];

   boot.initrd.availableKernelModules = [
      "xhci_pci"
      "nvme"
      "usb_storage"
      "sd_mod"
      "rtsx_pci_sdmmc"
   ];
   boot.initrd.kernelModules = [ ];
   boot.kernelModules = [ "kvm-intel" ];
   boot.extraModulePackages = [ ];

   fileSystems."/" = {
      device = "/dev/disk/by-uuid/bb77959e-03e6-42c9-8933-6e09ec55fddb";
      fsType = "ext4";
   };

   fileSystems."/boot" = {
      device = "/dev/disk/by-uuid/A211-B296";
      fsType = "vfat";
      options = [
         "fmask=0077"
         "dmask=0077"
      ];
   };

   swapDevices = [
      { device = "/dev/disk/by-uuid/9cc03614-345a-4726-b78a-58b2b5bbfa39"; }
   ];

   nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
   hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;


}
